task: 'maniskill_lift-cube'
steps: 2e6
env_num: 8
eval_episode_num: 10
action_repeat: 2
train_ratio: 512
time_limit: 200

seed: ${seed}
device: ${device}

size: [64, 64]
encoder:
  mlp_keys: '$^'
  cnn_keys: 'image'
decoder:
  mlp_keys: '$^'
  cnn_keys: 'image'

# ManiSkill2 configuration shared with TD-MPC2.
camera: base_camera
control_mode: null
render_size: 512

phys_trigger: false
phys_pair_clean: false
phys_trigger_pos: [0.0, -0.25, 0.08]
phys_trigger_size: 0.03
phys_trigger_rgba: [1.0, 0.0, 1.0, 1.0]
