task: 'myosuite_myo-key-turn'
steps: 1.01e6
env_num: 8
eval_episode_num: 10
action_repeat: 1
train_ratio: 512
time_limit: 100

seed: ${seed}
device: ${device}

size: [64, 64]
encoder:
  mlp_keys: '$^'
  cnn_keys: 'image'
decoder:
  mlp_keys: '$^'
  cnn_keys: 'image'

camera: hand_side_inter

phys_trigger: false
phys_pair_clean: false
phys_trigger_pos: [0.10, -0.20, 0.05]
phys_trigger_size: 0.025
phys_trigger_rgba: [1.0, 0.0, 1.0, 1.0]
