task: 'myosuite_myo-key-turn'
steps: 1.01e6
env_num: 8
eval_episode_num: 10
action_repeat: 1
train_ratio: 512
time_limit: 100

seed: ${seed}
device: ${device}

size: [96, 96]
encoder:
  mlp_keys: '$^'
  cnn_keys: 'image'
decoder:
  mlp_keys: '$^'
  cnn_keys: 'image'

camera: hand_side_inter
